name: fraud-env
channels:
  - conda-forge
dependencies:
  - python=3.10.11
  - pip
  - pip:
      - pandas
      - numpy
      - scikit-learn
      - mlflow==2.19.0
      - matplotlib
      - seaborn
      - dagshub